export const GET_ADVERTISEMENT_STATUS = "GET_ADVERTISEMENT_STATUS"
export const GET_ADVERTISEMENT_STATUS_SUCCESS = "GET_ADVERTISEMENT_STATUS_SUCCESS"
export const GET_ADVERTISEMENT_STATUS_FAIL = "GET_ADVERTISEMENT_STATUS_FAIL"