/* USER GET USER NOTIFICATION */
export const GET_USER_NOTIFICATION = "GET_USER_NOTIFICATION"
export const GET_USER_NOTIFICATION_SUCCESS = "GET_USER_NOTIFICATION_SUCCESS"
export const GET_USER_NOTIFICATION_FAIL = "GET_USER_NOTIFICATION_FAIL"
