/* UPDATE_ADVERTISEMENT */
export const UPDATE_ADVERTISEMENT = "UPDATE_ADVERTISEMENT"
export const UPDATE_ADVERTISEMENT_SUCCESS = "UPDATE_ADVERTISEMENT_SUCCESS"
export const UPDATE_ADVERTISEMENT_FAIL = "UPDATE_ADVERTISEMENT_FAIL"