/* UPDATE_USER_NOTIFICATION */
export const UPDATE_USER_NOTIFICATION = "UPDATE_USER_NOTIFICATION"
export const UPDATE_USER_NOTIFICATION_SUCCESS = "UPDATE_USER_NOTIFICATION_SUCCESS"
export const UPDATE_USER_NOTIFICATION_FAIL = "UPDATE_USER_NOTIFICATION_FAIL"