/*ADD ADVERTISEMENT */
export const ADD_ADVERTISEMENT = "ADD_ADVERTISEMENT"
export const ADD_ADVERTISEMENT_SUCCESS = "ADD_ADVERTISEMENT_SUCCESS"
export const ADD_ADVERTISEMENT_FAIL = "ADD_ADVERTISEMENT_FAIL"

